// Development-only transport. Its namespace must never be used for ordinary habit data.
export const NAMESPACE = 'loop-drive-integration-v1';
export const SCOPE = 'https://www.googleapis.com/auth/drive.appdata';
export const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;

export function validateRun(runId) {
  if (!UUID.test(runId)) throw new Error('Use a test run UUID generated by New test run.');
  return runId;
}

export function validateRecord(record, runId, accountId, evaluate) {
  if (record?.schema !== 1 || record.namespace !== NAMESPACE || record.runId !== validateRun(runId) ||
      record.accountId !== accountId || !UUID.test(record.operationId) ||
      !['android', 'browser'].includes(record.producer) ||
      !Number.isInteger(record.amountMillis) || record.amountMillis < 0 || record.amountMillis > 2147483647 ||
      typeof record.notes !== 'string' || record.notes.length > 10000) {
    throw new Error('Unsupported or invalid synthetic record; no data was applied or deleted.');
  }
  const expected = evaluate(record.amountMillis, record.notes);
  const actual = record.progress;
  if (!actual || actual.date !== expected.date || actual.amountMillis !== expected.amountMillis ||
      actual.notes !== expected.notes || actual.streakLength !== expected.streakLength ||
      !Number.isFinite(actual.score) || Math.abs(actual.score - expected.score) > 1e-10) {
    throw new Error('Android/browser core progress mismatch.');
  }
  return record;
}

export class DriveGate {
  constructor(token, accountId, evaluate) {
    this.token = token;
    this.accountId = accountId;
    this.evaluate = evaluate;
    this.metrics = { requests: 0, pages: 0, files: 0, downloadedBytes: 0, elapsedMs: 0 };
  }

  async request(url, options = {}) {
    this.metrics.requests++;
    const response = await fetch(url, {
      ...options,
      headers: { ...options.headers, Authorization: `Bearer ${this.token}` },
      cache: 'no-store',
      signal: AbortSignal.timeout(15000),
    });
    if (response.status === 401) throw new Error('Reconnect required: Google authorization expired.');
    if (!response.ok) throw new Error(`Drive request failed (${response.status}); retry this run.`);
    return response;
  }

  async publish(runId, amountMillis, notes) {
    const operationId = crypto.randomUUID();
    const record = {
      schema: 1, namespace: NAMESPACE, runId: validateRun(runId), operationId,
      producer: 'browser', accountId: this.accountId, amountMillis, notes,
      progress: this.evaluate(amountMillis, notes),
    };
    validateRecord(record, runId, this.accountId, this.evaluate);
    const metadata = {
      name: `${NAMESPACE}-${runId}-${operationId}.json`, mimeType: 'application/json', parents: ['appDataFolder'],
      appProperties: { namespace: NAMESPACE, runId },
    };
    const boundary = `loop_${crypto.randomUUID()}`;
    const body = `--${boundary}\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n${JSON.stringify(metadata)}\r\n` +
      `--${boundary}\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n${JSON.stringify(record)}\r\n--${boundary}--\r\n`;
    await this.request('https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id', {
      method: 'POST', headers: { 'Content-Type': `multipart/related; boundary=${boundary}` }, body,
    });
    return record;
  }

  async discover(runId) {
    validateRun(runId);
    this.metrics = { requests: 0, pages: 0, files: 0, downloadedBytes: 0, elapsedMs: 0 };
    const started = performance.now();
    const discovered = [];
    let pageToken;
    do {
      const params = new URLSearchParams({
        spaces: 'appDataFolder', pageSize: '2',
        fields: 'nextPageToken,incompleteSearch,files(id,name,mimeType,appProperties)',
        q: `trashed = false and appProperties has { key='namespace' and value='${NAMESPACE}' } and appProperties has { key='runId' and value='${runId}' }`,
      });
      if (pageToken) params.set('pageToken', pageToken);
      const page = await (await this.request(`https://www.googleapis.com/drive/v3/files?${params}`)).json();
      this.metrics.pages++;
      if (page.incompleteSearch || !Array.isArray(page.files)) throw new Error('Incomplete Drive discovery; retry.');
      for (const file of page.files) {
        if (file.appProperties?.namespace !== NAMESPACE || file.appProperties?.runId !== runId ||
            file.mimeType !== 'application/json') throw new Error('Unsafe discovery result; stopped.');
        const response = await this.request(`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(file.id)}?alt=media`);
        const content = await response.text();
        this.metrics.downloadedBytes += new TextEncoder().encode(content).length;
        const record = validateRecord(JSON.parse(content), runId, this.accountId, this.evaluate);
        if (file.name !== `${NAMESPACE}-${runId}-${record.operationId}.json`) throw new Error('Synthetic filename mismatch.');
        discovered.push({ id: file.id, record });
      }
      pageToken = page.nextPageToken;
    } while (pageToken);
    this.metrics.files = discovered.length;
    this.metrics.elapsedMs = Math.round(performance.now() - started);
    return discovered;
  }

  async cleanup(runId) {
    // Validate the entire run's metadata AND payloads before deleting any file.
    const files = await this.discover(runId);
    for (const file of files) {
      await this.request(`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(file.id)}`, { method: 'DELETE' });
    }
    return files.length;
  }
}
